const roles = [
  {
    id: 'supply-chain-trainee',
    slug: 'supply-chain-trainee',
    hireonId: 76,
    title: 'Supply Chain Trainee',
    department: 'Supply Chain',
    location: 'Bengaluru, India',
    type: 'Full-Time',
    mode: 'Hybrid',
    tags: ['Supply Chain', 'Entry Level', 'Full-Time'],
    summary: 'Kickstart your career in supply chain consulting by working alongside senior experts on real enterprise transformation projects.',
    responsibilities: [
      'Assist senior consultants in delivering supply chain transformation engagements for global clients.',
      'Support data collection, analysis, and visualization for supply chain diagnostics.',
      'Participate in workshops, client calls, and requirements gathering sessions.',
      'Document business processes, workflows, and project deliverables.',
      'Research industry trends in TMS, WMS, and supply chain technology.',
      'Help build presentations, dashboards, and client-facing reports.',
    ],
    qualifications: [
      "Bachelor's degree in Supply Chain, Logistics, Business, or related field.",
      '0–1 year of experience in supply chain, consulting, or operations.',
      'Strong analytical and problem-solving skills.',
      'Proficiency in Excel and PowerPoint; exposure to BI tools is a plus.',
      'Excellent communication and interpersonal skills.',
    ],
    characteristics: [
      'Eager to learn and grow in a fast-paced consulting environment.',
      'Detail-oriented with a structured approach to problem solving.',
      'Collaborative team player who takes initiative.',
      'Comfortable working with ambiguity and tight deadlines.',
    ],
  },
  {
    id: 'data-integration-consultant',
    slug: 'data-integration-consultant',
    hireonId: 75,
    title: 'Data Integration Consultant',
    department: 'Data Integration',
    location: 'Bengaluru, India',
    type: 'Full-Time',
    mode: 'Hybrid',
    tags: ['Data Integration', 'Mid Level', 'Full-Time'],
    summary: 'Design and implement enterprise data integration solutions that connect ERP, WMS, TMS, and analytics platforms for Fortune 500 clients.',
    responsibilities: [
      'Design end-to-end data integration architectures using ETL, API, and middleware platforms.',
      'Develop and maintain data pipelines connecting SAP, Blue Yonder, Snowflake, and other enterprise systems.',
      'Perform data mapping, transformation, and validation across heterogeneous data sources.',
      'Implement change data capture (CDC) and real-time streaming solutions.',
      'Collaborate with client stakeholders to gather integration requirements and document solutions.',
      'Conduct testing, troubleshooting, and performance optimization of integration workflows.',
      'Support client teams through go-live and post-implementation phases.',
    ],
    qualifications: [
      "Bachelor's or Master's degree in Computer Science, Information Systems, or related field.",
      '2–5 years of hands-on experience in data integration or ETL development.',
      'Strong proficiency in SQL, Python, and at least one ETL tool (SSIS, Talend, Informatica, etc.).',
      'Experience with API-based integrations (REST/GraphQL) and middleware platforms.',
      'Familiarity with cloud data warehouses (Snowflake, BigQuery, Redshift).',
      'Understanding of SAP or Blue Yonder integration patterns is a strong plus.',
    ],
    characteristics: [
      'Strong system-thinking mindset — able to see how data flows across an enterprise.',
      'Highly organized with meticulous attention to data quality and documentation.',
      'Proactive communicator who bridges technical and business teams effectively.',
      'Passionate about building scalable, reliable integration infrastructure.',
    ],
  },
  {
    id: 'functional-supply-chain-consultant',
    slug: 'functional-supply-chain-consultant',
    hireonId: 77,
    title: 'Functional Supply Chain Consultant',
    department: 'Supply Chain',
    location: 'Bengaluru, India / Remote',
    type: 'Full-Time',
    mode: 'Remote',
    tags: ['Supply Chain', 'Senior Level', 'Full-Time'],
    summary: 'Lead functional workstreams on large-scale supply chain transformation programs, leveraging deep expertise in TMS, WMS, and planning systems.',
    responsibilities: [
      'Lead functional design and configuration of TMS and WMS platforms (Blue Yonder, o9, SAP TM).',
      'Conduct business process analysis, gap assessments, and future-state design workshops.',
      'Manage client relationships and serve as the primary point of contact for functional workstreams.',
      'Collaborate with technical teams to translate business requirements into system configurations.',
      'Develop functional specifications, test scripts, and training documentation.',
      'Support change management and user adoption initiatives across client organizations.',
      'Mentor junior consultants and lead internal knowledge-sharing sessions.',
    ],
    qualifications: [
      "Bachelor's or Master's degree in Supply Chain, Engineering, Business, or related field.",
      '5+ years of supply chain consulting experience with at least 2 full-cycle TMS/WMS implementations.',
      'Deep functional knowledge of transportation management, warehouse operations, or demand planning.',
      'Proven track record delivering projects for enterprise clients in manufacturing, FMCG, or retail.',
      'Strong facilitation and executive communication skills.',
      'APICS CSCP or CLTD certification is a strong advantage.',
    ],
    characteristics: [
      'Strategic thinker who can connect operational details to business outcomes.',
      'Confident leader who drives alignment across complex stakeholder groups.',
      'Committed to delivering measurable, long-term value for clients.',
      'Energized by solving hard problems in complex global supply chains.',
    ],
  },
  {
    id: 'software-engineer',
    slug: 'software-engineer',
    hireonId: 74,
    title: 'Software Engineer',
    department: 'Engineering',
    location: 'Bengaluru, India',
    type: 'Full-Time',
    mode: 'Hybrid',
    tags: ['Engineering', 'Mid Level', 'Full-Time'],
    summary: 'Build and maintain enterprise-grade web applications, APIs, and agentic AI workflows that power Acespire\'s product and consulting delivery platforms.',
    responsibilities: [
      'Develop and maintain full-stack web applications using React, Node.js, and Python.',
      'Design and build RESTful APIs and GraphQL services for enterprise integrations.',
      'Collaborate with product and consulting teams to translate requirements into scalable solutions.',
      'Implement agentic AI workflows and LLM-powered automation pipelines.',
      'Write clean, testable, and well-documented code following engineering best practices.',
      'Debug and resolve software issues, ensuring application performance and security.',
      'Participate in code reviews, architecture discussions, and sprint planning.',
    ],
    qualifications: [
      "Bachelor's degree in Computer Science or related field.",
      '2–4 years of software development experience in a product or consulting environment.',
      'Proficiency in React, TypeScript, Node.js, and Python.',
      'Experience with cloud platforms (AWS, GCP, or Azure) and containerization (Docker, Kubernetes).',
      'Understanding of database design (PostgreSQL, MongoDB) and data pipelines.',
      'Exposure to LLMs, LangChain, or agentic AI frameworks is a strong plus.',
    ],
    characteristics: [
      'Able to think outside the box to deliver innovative and visually appealing solutions.',
      'Pays close attention to small details to ensure a polished and high-quality user experience.',
      'Open to feedback and capable of adjusting designs to meet evolving project needs.',
      'Collaborative team player who thrives in a fast-paced, mission-driven environment.',
    ],
  },
];

export default roles;